/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cidacastello.java.sao.domain.Interface;

import br.com.cidacastello.java.sao.domain.model.Maquina;
import br.com.cidacastello.java.sao.domain.model.Operacao;
import br.com.cidacastello.java.sao.domain.model.Peca;
import br.com.cidacastello.java.sao.util.JFrameUtils;
import java.awt.Color;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTextField;

/**
 *
 * @author Cida
 */
public class JFrameCalculoOciosidade extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCalculoOciosidade
     */
    JFrameMixProdutos frmMixProdutos;
    private Maquina[] maquina = new Maquina[10];
    private Peca[] peca = new Peca[7];
    private Operacao[] operacao = new Operacao[70];

    public JFrameCalculoOciosidade() {
        initComponents();
        // preencheValoresIniciais();
        setLocationRelativeTo(null);
        // calcularTempoOcupacao();
        dataAtual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCalculoOciosidade = new javax.swing.JPanel();
        jPanelDadosMaquina = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtM1 = new javax.swing.JTextField();
        txtM2 = new javax.swing.JTextField();
        txtM3 = new javax.swing.JTextField();
        txtM4 = new javax.swing.JTextField();
        txtM5 = new javax.swing.JTextField();
        txtM6 = new javax.swing.JTextField();
        txtM7 = new javax.swing.JTextField();
        txtM8 = new javax.swing.JTextField();
        txtM9 = new javax.swing.JTextField();
        txtM10 = new javax.swing.JTextField();
        txtTempOcupM1 = new javax.swing.JTextField();
        txtTempOcupM2 = new javax.swing.JTextField();
        txtTempOcupM3 = new javax.swing.JTextField();
        txtTempOcupM4 = new javax.swing.JTextField();
        txtTempOcupM5 = new javax.swing.JTextField();
        txtTempOcupM6 = new javax.swing.JTextField();
        txtTempOcupM7 = new javax.swing.JTextField();
        txtTempOcupM8 = new javax.swing.JTextField();
        txtTempOcupM9 = new javax.swing.JTextField();
        txtTempOcupM10 = new javax.swing.JTextField();
        txtOcioM1 = new javax.swing.JTextField();
        txtOcioM2 = new javax.swing.JTextField();
        txtOcioM3 = new javax.swing.JTextField();
        txtOcioM4 = new javax.swing.JTextField();
        txtOcioM5 = new javax.swing.JTextField();
        txtOcioM6 = new javax.swing.JTextField();
        txtOcioM7 = new javax.swing.JTextField();
        txtOcioM8 = new javax.swing.JTextField();
        txtOcioM9 = new javax.swing.JTextField();
        txtOcioM10 = new javax.swing.JTextField();
        jPanelMaqPeca = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtQtdeProd1 = new javax.swing.JTextField();
        txtQtdeProd2 = new javax.swing.JTextField();
        txtQtdeProd3 = new javax.swing.JTextField();
        txtQtdeProd4 = new javax.swing.JTextField();
        txtQtdeProd5 = new javax.swing.JTextField();
        txtQtdeProd6 = new javax.swing.JTextField();
        txtQtdeProd7 = new javax.swing.JTextField();
        txtP1M1 = new javax.swing.JTextField();
        txtP1M2 = new javax.swing.JTextField();
        txtP1M3 = new javax.swing.JTextField();
        txtP1M4 = new javax.swing.JTextField();
        txtP1M5 = new javax.swing.JTextField();
        txtP1M6 = new javax.swing.JTextField();
        txtP1M7 = new javax.swing.JTextField();
        txtP1M8 = new javax.swing.JTextField();
        txtP1M9 = new javax.swing.JTextField();
        txtP1M10 = new javax.swing.JTextField();
        txtP2M1 = new javax.swing.JTextField();
        txtP2M2 = new javax.swing.JTextField();
        txtP2M3 = new javax.swing.JTextField();
        txtP2M4 = new javax.swing.JTextField();
        txtP2M5 = new javax.swing.JTextField();
        txtP2M6 = new javax.swing.JTextField();
        txtP2M7 = new javax.swing.JTextField();
        txtP2M8 = new javax.swing.JTextField();
        txtP2M9 = new javax.swing.JTextField();
        txtP2M10 = new javax.swing.JTextField();
        txtP3M1 = new javax.swing.JTextField();
        txtP3M2 = new javax.swing.JTextField();
        txtP3M3 = new javax.swing.JTextField();
        txtP3M4 = new javax.swing.JTextField();
        txtP3M5 = new javax.swing.JTextField();
        txtP3M6 = new javax.swing.JTextField();
        txtP3M7 = new javax.swing.JTextField();
        txtP3M8 = new javax.swing.JTextField();
        txtP3M9 = new javax.swing.JTextField();
        txtP3M10 = new javax.swing.JTextField();
        txtP4M1 = new javax.swing.JTextField();
        txtP4M2 = new javax.swing.JTextField();
        txtP4M3 = new javax.swing.JTextField();
        txtP4M4 = new javax.swing.JTextField();
        txtP4M5 = new javax.swing.JTextField();
        txtP4M6 = new javax.swing.JTextField();
        txtP4M7 = new javax.swing.JTextField();
        txtP4M8 = new javax.swing.JTextField();
        txtP4M9 = new javax.swing.JTextField();
        txtP4M10 = new javax.swing.JTextField();
        txtP5M1 = new javax.swing.JTextField();
        txtP5M2 = new javax.swing.JTextField();
        txtP5M3 = new javax.swing.JTextField();
        txtP5M4 = new javax.swing.JTextField();
        txtP5M5 = new javax.swing.JTextField();
        txtP5M6 = new javax.swing.JTextField();
        txtP5M7 = new javax.swing.JTextField();
        txtP5M8 = new javax.swing.JTextField();
        txtP5M9 = new javax.swing.JTextField();
        txtP5M10 = new javax.swing.JTextField();
        txtP6M1 = new javax.swing.JTextField();
        txtP6M2 = new javax.swing.JTextField();
        txtP6M3 = new javax.swing.JTextField();
        txtP6M4 = new javax.swing.JTextField();
        txtP6M5 = new javax.swing.JTextField();
        txtP6M6 = new javax.swing.JTextField();
        txtP6M7 = new javax.swing.JTextField();
        txtP6M8 = new javax.swing.JTextField();
        txtP6M9 = new javax.swing.JTextField();
        txtP6M10 = new javax.swing.JTextField();
        txtP7M1 = new javax.swing.JTextField();
        txtP7M2 = new javax.swing.JTextField();
        txtP7M3 = new javax.swing.JTextField();
        txtP7M4 = new javax.swing.JTextField();
        txtP7M5 = new javax.swing.JTextField();
        txtP7M6 = new javax.swing.JTextField();
        txtP7M7 = new javax.swing.JTextField();
        txtP7M8 = new javax.swing.JTextField();
        txtP7M9 = new javax.swing.JTextField();
        txtP7M10 = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        btnCarregarValoresInciais = new javax.swing.JButton();
        btnMixProdutos = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SAO - Produção Diária");

        jPanelCalculoOciosidade.setLayout(null);

        jPanelDadosMaquina.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados das Máquinas"));
        jPanelDadosMaquina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("<html> Tempo Total Prod.<br> Disponível [tpt] </html>");
        jPanelDadosMaquina.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 41, 124, -1));

        jLabel2.setText("Tempo Ocupação [min.]");
        jPanelDadosMaquina.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, -1));

        jLabel3.setText("Ociosidade/Gargalo [min.]");
        jPanelDadosMaquina.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("M1");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        jPanelDadosMaquina.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 40, -1));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("M2");
        jLabel5.setOpaque(true);
        jPanelDadosMaquina.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 30, 40, -1));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("M10");
        jLabel6.setOpaque(true);
        jPanelDadosMaquina.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 40, -1));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("M3");
        jLabel14.setOpaque(true);
        jPanelDadosMaquina.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 30, 40, -1));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("M4");
        jLabel15.setOpaque(true);
        jPanelDadosMaquina.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 30, 40, -1));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("M5");
        jLabel16.setOpaque(true);
        jPanelDadosMaquina.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 30, 40, -1));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("M6");
        jLabel17.setOpaque(true);
        jPanelDadosMaquina.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 40, -1));

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("M7");
        jLabel18.setOpaque(true);
        jPanelDadosMaquina.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 30, 40, -1));

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("M8");
        jLabel19.setOpaque(true);
        jPanelDadosMaquina.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 30, 40, -1));

        jLabel20.setBackground(new java.awt.Color(204, 204, 204));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("M9");
        jLabel20.setOpaque(true);
        jPanelDadosMaquina.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 30, 40, -1));

        txtM1.setBackground(new java.awt.Color(255, 255, 0));
        txtM1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtM1.setName("txtM1"); // NOI18N
        jPanelDadosMaquina.add(txtM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 50, 30));

        txtM2.setBackground(new java.awt.Color(255, 255, 51));
        txtM2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtM2.setName("txtM2"); // NOI18N
        jPanelDadosMaquina.add(txtM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 49, 50, 30));

        txtM3.setBackground(new java.awt.Color(255, 255, 51));
        txtM3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtM3.setName("txtM3"); // NOI18N
        jPanelDadosMaquina.add(txtM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 49, 50, 30));

        txtM4.setBackground(new java.awt.Color(255, 255, 51));
        txtM4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtM4.setName("txtM4"); // NOI18N
        jPanelDadosMaquina.add(txtM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 49, 50, 30));

        txtM5.setBackground(new java.awt.Color(255, 255, 51));
        txtM5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtM5.setName("txtM5"); // NOI18N
        jPanelDadosMaquina.add(txtM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 49, 50, 30));

        txtM6.setBackground(new java.awt.Color(255, 255, 51));
        txtM6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtM6.setName("txtM6"); // NOI18N
        jPanelDadosMaquina.add(txtM6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 49, 50, 30));

        txtM7.setBackground(new java.awt.Color(255, 255, 51));
        txtM7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtM7.setName("txtM7"); // NOI18N
        jPanelDadosMaquina.add(txtM7, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 49, 50, 30));

        txtM8.setBackground(new java.awt.Color(255, 255, 51));
        txtM8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtM8.setName("txtM8"); // NOI18N
        jPanelDadosMaquina.add(txtM8, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 49, 50, 30));

        txtM9.setBackground(new java.awt.Color(255, 255, 51));
        txtM9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtM9.setName("txtM9"); // NOI18N
        jPanelDadosMaquina.add(txtM9, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 49, 50, 30));

        txtM10.setBackground(new java.awt.Color(255, 255, 51));
        txtM10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtM10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtM10.setName("txtM10"); // NOI18N
        jPanelDadosMaquina.add(txtM10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 50, 30));

        txtTempOcupM1.setEditable(false);
        txtTempOcupM1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTempOcupM1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtTempOcupM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, 30));

        txtTempOcupM2.setEditable(false);
        txtTempOcupM2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTempOcupM2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtTempOcupM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 90, 50, 30));

        txtTempOcupM3.setEditable(false);
        txtTempOcupM3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTempOcupM3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtTempOcupM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 90, 50, 30));

        txtTempOcupM4.setEditable(false);
        txtTempOcupM4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTempOcupM4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtTempOcupM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 90, 50, 30));

        txtTempOcupM5.setEditable(false);
        txtTempOcupM5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTempOcupM5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtTempOcupM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 90, 50, 30));

        txtTempOcupM6.setEditable(false);
        txtTempOcupM6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTempOcupM6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtTempOcupM6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 50, 30));

        txtTempOcupM7.setEditable(false);
        txtTempOcupM7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTempOcupM7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtTempOcupM7, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 90, 50, 30));

        txtTempOcupM8.setEditable(false);
        txtTempOcupM8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTempOcupM8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtTempOcupM8, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 90, 50, 30));

        txtTempOcupM9.setEditable(false);
        txtTempOcupM9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTempOcupM9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtTempOcupM9, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 90, 50, 30));

        txtTempOcupM10.setEditable(false);
        txtTempOcupM10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTempOcupM10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtTempOcupM10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 50, 30));

        txtOcioM1.setEditable(false);
        txtOcioM1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOcioM1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtOcioM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 50, 30));

        txtOcioM2.setEditable(false);
        txtOcioM2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOcioM2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtOcioM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 130, 50, 30));

        txtOcioM3.setEditable(false);
        txtOcioM3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOcioM3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtOcioM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 130, 50, 30));

        txtOcioM4.setEditable(false);
        txtOcioM4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOcioM4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtOcioM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 130, 50, 30));

        txtOcioM5.setEditable(false);
        txtOcioM5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOcioM5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtOcioM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 130, 50, 30));

        txtOcioM6.setEditable(false);
        txtOcioM6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOcioM6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtOcioM6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 50, 30));

        txtOcioM7.setEditable(false);
        txtOcioM7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOcioM7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtOcioM7, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 130, 50, 30));

        txtOcioM8.setEditable(false);
        txtOcioM8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOcioM8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtOcioM8, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 130, 50, 30));

        txtOcioM9.setEditable(false);
        txtOcioM9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOcioM9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtOcioM9, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 130, 50, 30));

        txtOcioM10.setEditable(false);
        txtOcioM10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtOcioM10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelDadosMaquina.add(txtOcioM10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 50, 30));

        jPanelCalculoOciosidade.add(jPanelDadosMaquina);
        jPanelDadosMaquina.setBounds(10, 50, 720, 180);

        jPanelMaqPeca.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo de Ocupação das Máquinas por Produto - [minutos]"));
        jPanelMaqPeca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Produto 7");
        jPanelMaqPeca.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel8.setText("Produto 1");
        jPanelMaqPeca.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel9.setText("Produto 2");
        jPanelMaqPeca.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel10.setText("Produto 3");
        jPanelMaqPeca.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel11.setText("Produto 4");
        jPanelMaqPeca.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel12.setText("Produto 5");
        jPanelMaqPeca.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel13.setText("Produto 6");
        jPanelMaqPeca.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("z");
        jLabel21.setOpaque(true);
        jPanelMaqPeca.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 26, 20, 20));

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("M1");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel22.setOpaque(true);
        jPanelMaqPeca.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 40, -1));

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("M2");
        jLabel23.setOpaque(true);
        jPanelMaqPeca.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 30, 40, -1));

        jLabel24.setBackground(new java.awt.Color(204, 204, 204));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("M3");
        jLabel24.setOpaque(true);
        jPanelMaqPeca.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 30, 40, -1));

        jLabel25.setBackground(new java.awt.Color(204, 204, 204));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("M4");
        jLabel25.setOpaque(true);
        jPanelMaqPeca.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 30, 40, -1));

        jLabel26.setBackground(new java.awt.Color(204, 204, 204));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("M5");
        jLabel26.setOpaque(true);
        jPanelMaqPeca.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 30, 40, -1));

        jLabel27.setBackground(new java.awt.Color(204, 204, 204));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("M6");
        jLabel27.setOpaque(true);
        jPanelMaqPeca.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 40, -1));

        jLabel28.setBackground(new java.awt.Color(204, 204, 204));
        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("M7");
        jLabel28.setOpaque(true);
        jPanelMaqPeca.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 30, 40, -1));

        jLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("M8");
        jLabel29.setOpaque(true);
        jPanelMaqPeca.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 30, 40, -1));

        jLabel30.setBackground(new java.awt.Color(204, 204, 204));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("M9");
        jLabel30.setOpaque(true);
        jPanelMaqPeca.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 30, 40, -1));

        jLabel31.setBackground(new java.awt.Color(204, 204, 204));
        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("M10");
        jLabel31.setOpaque(true);
        jPanelMaqPeca.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 40, -1));

        txtQtdeProd1.setBackground(new java.awt.Color(255, 255, 0));
        txtQtdeProd1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtQtdeProd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 50, 30));

        txtQtdeProd2.setBackground(new java.awt.Color(255, 255, 0));
        txtQtdeProd2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtQtdeProd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 50, 30));

        txtQtdeProd3.setBackground(new java.awt.Color(255, 255, 0));
        txtQtdeProd3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtQtdeProd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 50, 30));

        txtQtdeProd4.setBackground(new java.awt.Color(255, 255, 0));
        txtQtdeProd4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtQtdeProd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 50, 30));

        txtQtdeProd5.setBackground(new java.awt.Color(255, 255, 0));
        txtQtdeProd5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtQtdeProd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 50, 30));

        txtQtdeProd6.setBackground(new java.awt.Color(255, 255, 0));
        txtQtdeProd6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtQtdeProd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 50, 30));

        txtQtdeProd7.setBackground(new java.awt.Color(255, 255, 0));
        txtQtdeProd7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtQtdeProd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 50, 30));

        txtP1M1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtP1M1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP1M1ActionPerformed(evt);
            }
        });
        jPanelMaqPeca.add(txtP1M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 50, 30));

        txtP1M2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP1M2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 50, 46, 30));

        txtP1M3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP1M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 50, 46, 30));

        txtP1M4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP1M4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 50, 46, 30));

        txtP1M5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP1M5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 50, 46, 30));

        txtP1M6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP1M6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 46, 30));

        txtP1M7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP1M7, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 50, 46, 30));

        txtP1M8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP1M8, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 50, 46, 30));

        txtP1M9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP1M9, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 50, 46, 30));

        txtP1M10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP1M10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 50, 30));

        txtP2M1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP2M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, 30));

        txtP2M2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP2M2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 90, 50, 30));

        txtP2M3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP2M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 90, 50, 30));

        txtP2M4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP2M4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 90, 50, 30));

        txtP2M5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP2M5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 90, 50, 30));

        txtP2M6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP2M6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 50, 30));

        txtP2M7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP2M7, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 90, 50, 30));

        txtP2M8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP2M8, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 90, 50, 30));

        txtP2M9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP2M9, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 90, 50, 30));

        txtP2M10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP2M10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 50, 30));

        txtP3M1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP3M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 50, 30));

        txtP3M2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP3M2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 130, 50, 30));

        txtP3M3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP3M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 130, 50, 30));

        txtP3M4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP3M4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 130, 50, 30));

        txtP3M5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP3M5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 130, 50, 30));

        txtP3M6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP3M6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 50, 30));

        txtP3M7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP3M7, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 130, 50, 30));

        txtP3M8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP3M8, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 130, 50, 30));

        txtP3M9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP3M9, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 130, 50, 30));

        txtP3M10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP3M10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 50, 30));

        txtP4M1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP4M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 50, 30));

        txtP4M2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP4M2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 170, 50, 30));

        txtP4M3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP4M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 170, 50, 30));

        txtP4M4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP4M4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 170, 50, 30));

        txtP4M5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP4M5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 170, 50, 30));

        txtP4M6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP4M6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 50, 30));

        txtP4M7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP4M7, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 170, 50, 30));

        txtP4M8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP4M8, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 170, 50, 30));

        txtP4M9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP4M9, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 170, 50, 30));

        txtP4M10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP4M10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 50, 30));

        txtP5M1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP5M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 50, 30));

        txtP5M2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP5M2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 210, 50, 30));

        txtP5M3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP5M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 210, 50, 30));

        txtP5M4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP5M4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 210, 50, 30));

        txtP5M5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP5M5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 210, 50, 30));

        txtP5M6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP5M6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 50, 30));

        txtP5M7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP5M7, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 210, 50, 30));

        txtP5M8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP5M8, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 210, 50, 30));

        txtP5M9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP5M9, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 210, 50, 30));

        txtP5M10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP5M10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 50, 30));

        txtP6M1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP6M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 50, 30));

        txtP6M2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP6M2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 250, 50, 30));

        txtP6M3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP6M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 250, 50, 30));

        txtP6M4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP6M4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 250, 50, 30));

        txtP6M5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP6M5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 250, 50, 30));

        txtP6M6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP6M6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 50, 30));

        txtP6M7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP6M7, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 250, 50, 30));

        txtP6M8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP6M8, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 250, 50, 30));

        txtP6M9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP6M9, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 250, 50, 30));

        txtP6M10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP6M10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 50, 30));

        txtP7M1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP7M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 50, 30));

        txtP7M2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP7M2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 290, 50, 30));

        txtP7M3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP7M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 290, 50, 30));

        txtP7M4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP7M4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 290, 50, 30));

        txtP7M5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP7M5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 290, 50, 30));

        txtP7M6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP7M6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 50, 30));

        txtP7M7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP7M7, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 290, 50, 30));

        txtP7M8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP7M8, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 290, 50, 30));

        txtP7M9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP7M9, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 290, 50, 30));

        txtP7M10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanelMaqPeca.add(txtP7M10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 50, 30));

        jPanelCalculoOciosidade.add(jPanelMaqPeca);
        jPanelMaqPeca.setBounds(10, 240, 720, 340);

        jPanelButtons.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCarregarValoresInciais.setText("<html><body><center>Carregar Valores Iniciais</center></body></html>");
        btnCarregarValoresInciais.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnCarregarValoresInciais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarValoresInciaisActionPerformed(evt);
            }
        });
        jPanelButtons.add(btnCarregarValoresInciais, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 20, 120, 40));

        btnMixProdutos.setText("Mix de Produtos");
        btnMixProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMixProdutosActionPerformed(evt);
            }
        });
        jPanelButtons.add(btnMixProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanelButtons.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, -1));

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        jPanelButtons.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, -1));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanelButtons.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanelButtons.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, -1));

        jPanelCalculoOciosidade.add(jPanelButtons);
        jPanelButtons.setBounds(740, 60, 140, 290);

        lblData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setText("Produção do dia:");
        jPanelCalculoOciosidade.add(lblData);
        lblData.setBounds(20, 10, 700, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCalculoOciosidade, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCalculoOciosidade, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarValoresInciaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarValoresInciaisActionPerformed
        // TODO add your handling code here:
        preencheValoresIniciais();
    }//GEN-LAST:event_btnCarregarValoresInciaisActionPerformed

    private void btnMixProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMixProdutosActionPerformed
        // TODO add your handling code here:  

        frmMixProdutos = new JFrameMixProdutos(maquina);
        if (frmMixProdutos == null) {
            frmMixProdutos = new JFrameMixProdutos();
        }

        frmMixProdutos.setLocationRelativeTo(null);
        frmMixProdutos.setVisible(true);
        frmMixProdutos.setResizable(false);


        //calcularTempoOcupacao();
    }//GEN-LAST:event_btnMixProdutosActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:carregarValoresAtuais();
        carregarValoresAtuais();
        calcularTempoOcupacao();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtP1M1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP1M1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP1M1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculoOciosidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculoOciosidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculoOciosidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculoOciosidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCalculoOciosidade().setVisible(true);
            }
        });
    }

    private void dataAtual() {
        Date data = new Date();
        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
        lblData.setText("Produção do dia: " + dataFormatada.format(data));
    }

    private void limpar() {
        JFrameUtils.cleanJTextFields(jPanelDadosMaquina.getComponents());
        JFrameUtils.cleanJTextFields(jPanelMaqPeca.getComponents());
/*
        Component[] components = jPanelDadosMaquina.getComponents();
        int i = 1;
        String texto = "txtM" + i;
        String nome;

        for (Component c : components) {
            if (c instanceof JTextField) {
                nome = c.getName();

                if (texto.equals(nome)) {
                    System.out.println(c.getName());
                    i++;
                    texto="txtM"+i;
                }
        }
}*/
        /*alterado a propriedade name do txtM1*/
    }

    private void calcularTempoOcupacao() {

        DecimalFormat df = new DecimalFormat("0.00");
        //  System.out.println("op " + operacao[0].getPeca().getQuantidade() + " tempo " + operacao[0].getTempoOcupacaoMaquinaPeca() + "maq " + operacao[0].getMaquina().getDescricaoDaMaquina());
        double tempo = 0;

        for (int i = 0; i <= 60; i += 10) {
            if (operacao[i] != null) {
                if (operacao[i].getPeca() != null && operacao[i].getTempoOcupacaoMaquinaPeca() != 0) {
                    operacao[i].setTempoTotalOperacao(operacao[i].getPeca().getQuantidade() * operacao[i].getTempoOcupacaoMaquinaPeca());
                    tempo += operacao[i].getTempoTotalOperacao();
                }
            }
        }



        maquina[0].setTempoTotalOcupacao(tempo);
        maquina[0].setOciosidade_gargalo(maquina[0].getTempoTotal() - maquina[0].getTempoTotalOcupacao());
        txtTempOcupM1.setText(Double.toString(maquina[0].getTempoTotalOcupacao()));
        txtOcioM1.setText(String.format("%.2f", maquina[0].getOciosidade_gargalo()).replace(",", "."));
        this.setColorJText(txtOcioM1, this.maquina[0].getOciosidade_gargalo());


        tempo = 0;
        for (int i = 1; i <= 61; i += 10) {
            if (operacao[i] != null) {
                if (operacao[i].getPeca() != null && operacao[i].getTempoOcupacaoMaquinaPeca() != 0) {
                    tempo += (operacao[i].getPeca().getQuantidade() * operacao[i].getTempoOcupacaoMaquinaPeca());
                }
            }
        }

        maquina[1].setTempoTotalOcupacao(tempo);
        maquina[1].setOciosidade_gargalo(maquina[1].getTempoTotal() - maquina[1].getTempoTotalOcupacao());
        txtTempOcupM2.setText(Double.toString(maquina[1].getTempoTotalOcupacao()));
        txtOcioM2.setText(df.format(maquina[1].getOciosidade_gargalo()).replace(",", "."));
        this.setColorJText(txtOcioM2, this.maquina[1].getOciosidade_gargalo());

        tempo = 0;
        for (int i = 2; i <= 62; i += 10) {
            if (operacao[i] != null) {
                if (operacao[i].getPeca() != null && operacao[i].getTempoOcupacaoMaquinaPeca() != 0) {
                    tempo += (operacao[i].getPeca().getQuantidade() * operacao[i].getTempoOcupacaoMaquinaPeca());
                }
            }
        }

        maquina[2].setTempoTotalOcupacao(tempo);
        maquina[2].setOciosidade_gargalo(maquina[2].getTempoTotal() - maquina[2].getTempoTotalOcupacao());
        txtTempOcupM3.setText(Double.toString(maquina[2].getTempoTotalOcupacao()));
        txtOcioM3.setText(df.format(maquina[2].getOciosidade_gargalo()).replace(",", "."));
        this.setColorJText(txtOcioM3, this.maquina[2].getOciosidade_gargalo());

        tempo = 0;
        for (int i = 3; i <= 63; i += 10) {
            if (operacao[i] != null) {
                if (operacao[i].getPeca() != null && operacao[i].getTempoOcupacaoMaquinaPeca() != 0) {
                    tempo += (operacao[i].getPeca().getQuantidade() * operacao[i].getTempoOcupacaoMaquinaPeca());
                }
            }
        }

        maquina[3].setTempoTotalOcupacao(tempo);
        maquina[3].setOciosidade_gargalo(maquina[3].getTempoTotal() - maquina[3].getTempoTotalOcupacao());
        txtTempOcupM4.setText(Double.toString(maquina[3].getTempoTotalOcupacao()));
        txtOcioM4.setText(df.format(maquina[3].getOciosidade_gargalo()).replace(",", "."));
        this.setColorJText(txtOcioM4, this.maquina[3].getOciosidade_gargalo());

        tempo = 0;
        for (int i = 4; i <= 64; i += 10) {
            if (operacao[i] != null) {
                if (operacao[i].getPeca() != null && operacao[i].getTempoOcupacaoMaquinaPeca() != 0) {
                    tempo += (operacao[i].getPeca().getQuantidade() * operacao[i].getTempoOcupacaoMaquinaPeca());
                }
            }
        }

        maquina[4].setTempoTotalOcupacao(tempo);
        maquina[4].setOciosidade_gargalo(maquina[4].getTempoTotal() - maquina[4].getTempoTotalOcupacao());
        txtTempOcupM5.setText(Double.toString(maquina[4].getTempoTotalOcupacao()));
        txtOcioM5.setText(df.format(maquina[4].getOciosidade_gargalo()).replace(",", "."));
        this.setColorJText(txtOcioM5, this.maquina[4].getOciosidade_gargalo());

        tempo = 0;
        for (int i = 5; i <= 65; i += 10) {
            if (operacao[i] != null) {
                if (operacao[i].getPeca() != null && operacao[i].getTempoOcupacaoMaquinaPeca() != 0) {
                    tempo += (operacao[i].getPeca().getQuantidade() * operacao[i].getTempoOcupacaoMaquinaPeca());
                }
            }
        }

        maquina[5].setTempoTotalOcupacao(tempo);
        maquina[5].setOciosidade_gargalo(maquina[5].getTempoTotal() - maquina[5].getTempoTotalOcupacao());
        txtTempOcupM6.setText(Double.toString(maquina[5].getTempoTotalOcupacao()));
        txtOcioM6.setText(df.format(maquina[5].getOciosidade_gargalo()).replace(",", "."));
        this.setColorJText(txtOcioM6, this.maquina[5].getOciosidade_gargalo());

        tempo = 0;
        for (int i = 6; i <= 66; i += 10) {
            if (operacao[i] != null) {
                if (operacao[i].getPeca() != null && operacao[i].getTempoOcupacaoMaquinaPeca() != 0) {
                    tempo += (operacao[i].getPeca().getQuantidade() * operacao[i].getTempoOcupacaoMaquinaPeca());
                }
            }
        }

        maquina[6].setTempoTotalOcupacao(tempo);
        maquina[6].setOciosidade_gargalo(maquina[6].getTempoTotal() - maquina[6].getTempoTotalOcupacao());
        txtTempOcupM7.setText(Double.toString(maquina[6].getTempoTotalOcupacao()));
        txtOcioM7.setText(df.format(maquina[6].getOciosidade_gargalo()).replace(",", "."));
        this.setColorJText(txtOcioM7, this.maquina[6].getOciosidade_gargalo());

        tempo = 0;
        for (int i = 7; i <= 67; i += 10) {
            if (operacao[i] != null) {
                if (operacao[i].getPeca() != null && operacao[i].getTempoOcupacaoMaquinaPeca() != 0) {
                    tempo += (operacao[i].getPeca().getQuantidade() * operacao[i].getTempoOcupacaoMaquinaPeca());
                }
            }
        }

        maquina[7].setTempoTotalOcupacao(tempo);
        maquina[7].setOciosidade_gargalo(maquina[7].getTempoTotal() - maquina[7].getTempoTotalOcupacao());
        txtTempOcupM8.setText(Double.toString(maquina[7].getTempoTotalOcupacao()));
        txtOcioM8.setText(df.format(maquina[7].getOciosidade_gargalo()).replace(",", "."));
        this.setColorJText(txtOcioM8, this.maquina[7].getOciosidade_gargalo());

        tempo = 0;
        for (int i = 8; i <= 68; i += 10) {
            if (operacao[i] != null) {
                if (operacao[i].getPeca() != null && operacao[i].getTempoOcupacaoMaquinaPeca() != 0) {
                    tempo += (operacao[i].getPeca().getQuantidade() * operacao[i].getTempoOcupacaoMaquinaPeca());
                }
            }
        }

        maquina[8].setTempoTotalOcupacao(tempo);
        maquina[8].setOciosidade_gargalo(maquina[8].getTempoTotal() - maquina[8].getTempoTotalOcupacao());
        txtTempOcupM9.setText(Double.toString(maquina[8].getTempoTotalOcupacao()));
        txtOcioM9.setText(df.format(maquina[8].getOciosidade_gargalo()).replace(",", "."));
        this.setColorJText(txtOcioM9, this.maquina[8].getOciosidade_gargalo());

        tempo = 0;
        for (int i = 9; i <= 69; i += 10) {
            if (operacao[i] != null) {
                if (operacao[i].getPeca() != null && operacao[i].getTempoOcupacaoMaquinaPeca() != 0) {
                    tempo += (operacao[i].getPeca().getQuantidade() * operacao[i].getTempoOcupacaoMaquinaPeca());
                }
            }
        }

        maquina[9].setTempoTotalOcupacao(tempo);
        maquina[9].setOciosidade_gargalo(maquina[9].getTempoTotal() - maquina[9].getTempoTotalOcupacao());
        txtTempOcupM10.setText(Double.toString(maquina[9].getTempoTotalOcupacao()));
        txtOcioM10.setText(df.format(maquina[9].getOciosidade_gargalo()).replace(",", "."));
        this.setColorJText(txtOcioM10, this.maquina[9].getOciosidade_gargalo());
        tempo = 0;
        
        //set se maquina gargalo ou não
        //incluído em 18/08/2015
        for(int i = 0; i < maquina.length; i++){
            
            if(maquina[i].getTempoTotalOcupacao() > 0){
                maquina[i].setGargalo(false);
            }
            else{
                maquina[i].setGargalo(true);
            }
        }
    }

    private void setColorJText(JTextField text, double valor) {
        if (valor <= 0) {
            text.setBackground(Color.red);
            text.setForeground(Color.white);
        } else {
            text.setBackground(Color.green);
            text.setForeground(Color.black);
        }

    }

    private void carregarValoresAtuais() {
        //maquina
        maquina[0].setTempoTotal(Double.parseDouble(txtM1.getText()));
        maquina[1].setTempoTotal(Double.parseDouble(txtM2.getText()));
        maquina[2].setTempoTotal(Double.parseDouble(txtM3.getText()));
        maquina[3].setTempoTotal(Double.parseDouble(txtM4.getText()));
        maquina[4].setTempoTotal(Double.parseDouble(txtM5.getText()));
        maquina[5].setTempoTotal(Double.parseDouble(txtM6.getText()));
        maquina[6].setTempoTotal(Double.parseDouble(txtM7.getText()));
        maquina[7].setTempoTotal(Double.parseDouble(txtM8.getText()));
        maquina[8].setTempoTotal(Double.parseDouble(txtM9.getText()));
        maquina[9].setTempoTotal(Double.parseDouble(txtM10.getText()));

        //quantidade        
        this.validarEntradaQtdePeca(txtQtdeProd1, 0);
        this.validarEntradaQtdePeca(txtQtdeProd2, 1);
        this.validarEntradaQtdePeca(txtQtdeProd3, 2);
        this.validarEntradaQtdePeca(txtQtdeProd4, 3);
        this.validarEntradaQtdePeca(txtQtdeProd5, 4);
        this.validarEntradaQtdePeca(txtQtdeProd6, 5);
        this.validarEntradaQtdePeca(txtQtdeProd7, 6);

        //tempos das operações
        this.carregarEntradaTempos(txtP1M1, 0);
        this.carregarEntradaTempos(txtP1M2, 1);
        this.carregarEntradaTempos(txtP1M3, 2);
        this.carregarEntradaTempos(txtP1M4, 3);
        this.carregarEntradaTempos(txtP1M5, 4);
        this.carregarEntradaTempos(txtP1M6, 5);
        this.carregarEntradaTempos(txtP1M7, 6);
        this.carregarEntradaTempos(txtP1M8, 7);
        this.carregarEntradaTempos(txtP1M9, 8);
        this.carregarEntradaTempos(txtP1M10, 9);

        this.carregarEntradaTempos(txtP2M1, 10);
        this.carregarEntradaTempos(txtP2M2, 11);
        this.carregarEntradaTempos(txtP2M3, 12);
        this.carregarEntradaTempos(txtP2M4, 13);
        this.carregarEntradaTempos(txtP2M5, 14);
        this.carregarEntradaTempos(txtP2M6, 15);
        this.carregarEntradaTempos(txtP2M7, 16);
        this.carregarEntradaTempos(txtP2M8, 17);
        this.carregarEntradaTempos(txtP2M9, 18);
        this.carregarEntradaTempos(txtP2M10, 19);

        this.carregarEntradaTempos(txtP3M1, 0 + 20);
        this.carregarEntradaTempos(txtP3M2, 1 + 20);
        this.carregarEntradaTempos(txtP3M3, 2 + 20);
        this.carregarEntradaTempos(txtP3M4, 3 + 20);
        this.carregarEntradaTempos(txtP3M5, 4 + 20);
        this.carregarEntradaTempos(txtP3M6, 5 + 20);
        this.carregarEntradaTempos(txtP3M7, 6 + 20);
        this.carregarEntradaTempos(txtP3M8, 7 + 20);
        this.carregarEntradaTempos(txtP3M9, 8 + 20);
        this.carregarEntradaTempos(txtP3M10, 9 + 20);

        this.carregarEntradaTempos(txtP4M1, 30);
        this.carregarEntradaTempos(txtP4M2, 31);
        this.carregarEntradaTempos(txtP4M3, 32);
        this.carregarEntradaTempos(txtP4M4, 33);
        this.carregarEntradaTempos(txtP4M5, 34);
        this.carregarEntradaTempos(txtP4M6, 35);
        this.carregarEntradaTempos(txtP4M7, 36);
        this.carregarEntradaTempos(txtP4M8, 37);
        this.carregarEntradaTempos(txtP4M9, 38);
        this.carregarEntradaTempos(txtP4M10, 39);

        this.carregarEntradaTempos(txtP5M1, 40);
        this.carregarEntradaTempos(txtP5M2, 41);
        this.carregarEntradaTempos(txtP5M3, 42);
        this.carregarEntradaTempos(txtP5M4, 43);
        this.carregarEntradaTempos(txtP5M5, 44);
        this.carregarEntradaTempos(txtP5M6, 45);
        this.carregarEntradaTempos(txtP5M7, 46);
        this.carregarEntradaTempos(txtP5M8, 47);
        this.carregarEntradaTempos(txtP5M9, 48);
        this.carregarEntradaTempos(txtP5M10, 49);

        this.carregarEntradaTempos(txtP6M1, 50);
        this.carregarEntradaTempos(txtP6M2, 51);
        this.carregarEntradaTempos(txtP6M3, 52);
        this.carregarEntradaTempos(txtP6M4, 53);
        this.carregarEntradaTempos(txtP6M5, 54);
        this.carregarEntradaTempos(txtP6M6, 55);
        this.carregarEntradaTempos(txtP6M7, 56);
        this.carregarEntradaTempos(txtP6M8, 57);
        this.carregarEntradaTempos(txtP6M9, 58);
        this.carregarEntradaTempos(txtP6M10, 59);

        this.carregarEntradaTempos(txtP7M1, 60);
        this.carregarEntradaTempos(txtP7M2, 61);
        this.carregarEntradaTempos(txtP7M3, 62);
        this.carregarEntradaTempos(txtP7M4, 63);
        this.carregarEntradaTempos(txtP7M5, 64);
        this.carregarEntradaTempos(txtP7M6, 65);
        this.carregarEntradaTempos(txtP7M7, 66);
        this.carregarEntradaTempos(txtP7M8, 67);
        this.carregarEntradaTempos(txtP7M9, 68);
        this.carregarEntradaTempos(txtP7M10, 69);

    }

    private void carregarEntradaTempos(JTextField text, int indice) {
        if (!text.getText().isEmpty() && text.getText().trim().length() > 0) {
            operacao[indice].setTempoOcupacaoMaquinaPeca(Double.parseDouble(text.getText()));
        } else {
            operacao[indice].setTempoOcupacaoMaquinaPeca(0);
        }
    }

    private void validarEntradaQtdePeca(JTextField text, int indice) {
        if (!text.getText().isEmpty() && text.getText().trim().length() > 0) {
            peca[indice].setQuantidade(Integer.parseInt(text.getText()));
        } else {
            peca[indice].setQuantidade(0);
        }
    }

    //preencher temporariamente os controles igual tem no IAS
    private void preencheValoresIniciais() {

        //set valores no vetor maquinas
        for (int i = 0; i < maquina.length; i++) {
            maquina[i] = new Maquina();
            maquina[i].setDescricaoDaMaquina("M_" + i + 1);
            maquina[i].setTempoTotal(480);
        }

        //set valores nas text das máquinas
        txtM1.setText(Double.toString(maquina[0].getTempoTotal()));
        txtM2.setText(String.valueOf(maquina[1].getTempoTotal()));
        txtM3.setText(Double.toString(maquina[2].getTempoTotal()));
        txtM4.setText(Double.toString(maquina[3].getTempoTotal()));
        txtM5.setText(Double.toString(maquina[4].getTempoTotal()));
        txtM6.setText(Double.toString(maquina[5].getTempoTotal()));
        txtM7.setText(Double.toString(maquina[6].getTempoTotal()));
        txtM8.setText(Double.toString(maquina[7].getTempoTotal()));
        txtM9.setText(Double.toString(maquina[8].getTempoTotal()));
        txtM10.setText(Double.toString(maquina[9].getTempoTotal()));

        //inicializa peca
        for (int i = 0; i < peca.length; i++) {
            peca[i] = new Peca();
            peca[i].setDescricao("P_" + i + 1);
            peca[i].setPrazoEntrega(0);
            peca[i].setMargemContribuicao(0);
        }
        //set valores nas text quantidade de produtos das pecas
        
        peca[0].setQuantidade(8);
        txtQtdeProd1.setText(Integer.toString(peca[0].getQuantidade()));
        
        peca[1].setQuantidade(23);
        txtQtdeProd2.setText(Integer.toString(peca[1].getQuantidade()));
        
        peca[2].setQuantidade(20);
        txtQtdeProd3.setText(Integer.toString(peca[2].getQuantidade()));
        
        peca[3].setQuantidade(15);
        txtQtdeProd4.setText(Integer.toString(peca[3].getQuantidade()));
        
        peca[4].setQuantidade(8);
        txtQtdeProd5.setText(Integer.toString(peca[4].getQuantidade()));
        
        peca[5].setQuantidade(4);
        txtQtdeProd6.setText(Integer.toString(peca[5].getQuantidade()));
        
        peca[6].setQuantidade(1);
        txtQtdeProd7.setText(Integer.toString(peca[6].getQuantidade()));


        //inicializa as operações

        for (int i = 0; i < operacao.length; i++) {
            operacao[i] = new Operacao();
            // operacao[i] = null;
        }

        int codPeca = 1;
        int codMaquina = 1;
        String texto;
        
        for (int i = 0; i < 10; i++) {
            
            operacao[i].setDescricao(texto = "P" + codPeca + "M" + codMaquina);
            operacao[i].setPeca(peca[0]);
            operacao[i].setMaquina(maquina[i]);
            
            operacao[i + 10].setDescricao(texto = "P" + (codPeca + 1) + "M" + (codMaquina + 1));
            operacao[i + 10].setPeca(peca[1]);
            operacao[i].setMaquina(maquina[i]);

            operacao[i + 20].setDescricao(texto = "P" + (codPeca + 2) + "M" + (codMaquina + 2));
            operacao[i + 20].setPeca(peca[2]);
            operacao[i].setMaquina(maquina[i]);

            operacao[i + 30].setDescricao(texto = "P" + (codPeca + 3) + "M" + (codMaquina + 3));
            operacao[i + 30].setPeca(peca[3]);
            operacao[i].setMaquina(maquina[i]);

            operacao[i + 40].setDescricao(texto = "P" + (codPeca + 4) + "M" + (codMaquina + 4));
            operacao[i + 40].setPeca(peca[4]);
            operacao[i].setMaquina(maquina[i]);

            operacao[i + 50].setDescricao(texto = "P" + (codPeca + 5) + "M" + (codMaquina + 5));
            operacao[i + 50].setPeca(peca[5]);
            operacao[i].setMaquina(maquina[i]);

            operacao[i + 60].setDescricao(texto = "P" + (codPeca + 6) + "M" + (codMaquina + 6));
            operacao[i + 60].setPeca(peca[6]);
            operacao[i].setMaquina(maquina[i]);

        }


        //set tempo de ocupação nas máquinas por operação
        //maquina 1

        operacao[0].setTempoOcupacaoMaquinaPeca(10.6);
        txtP1M1.setText(Double.toString(operacao[0].getTempoOcupacaoMaquinaPeca()));

        operacao[10].setTempoOcupacaoMaquinaPeca(0.3);
        txtP2M1.setText(Double.toString(operacao[10].getTempoOcupacaoMaquinaPeca()));

        operacao[20].setTempoOcupacaoMaquinaPeca(11);
        txtP3M1.setText(Double.toString(operacao[20].getTempoOcupacaoMaquinaPeca()));

        operacao[30].setTempoOcupacaoMaquinaPeca(7.7);
        txtP4M1.setText(Double.toString(operacao[30].getTempoOcupacaoMaquinaPeca()));

        operacao[40].setTempoOcupacaoMaquinaPeca(0.4);
        txtP5M1.setText(Double.toString(operacao[40].getTempoOcupacaoMaquinaPeca()));

        //maquina 2

        operacao[11].setTempoOcupacaoMaquinaPeca(4.1);
        txtP2M2.setText(Double.toString(operacao[11].getTempoOcupacaoMaquinaPeca()));

        operacao[21].setTempoOcupacaoMaquinaPeca(5.2);
        txtP3M2.setText(Double.toString(operacao[21].getTempoOcupacaoMaquinaPeca()));

        operacao[31].setTempoOcupacaoMaquinaPeca(4.1);
        txtP4M2.setText(Double.toString(operacao[31].getTempoOcupacaoMaquinaPeca()));

        operacao[22].setTempoOcupacaoMaquinaPeca(1.5);
        txtP2M3.setText(Double.toString(operacao[22].getTempoOcupacaoMaquinaPeca()));

        operacao[32].setTempoOcupacaoMaquinaPeca(1.5);
        txtP3M3.setText(Double.toString(operacao[32].getTempoOcupacaoMaquinaPeca()));

        operacao[42].setTempoOcupacaoMaquinaPeca(0.7);
        txtP4M3.setText(Double.toString(operacao[42].getTempoOcupacaoMaquinaPeca()));

        operacao[62].setTempoOcupacaoMaquinaPeca(26.2);
        txtP7M3.setText(Double.toString(operacao[62].getTempoOcupacaoMaquinaPeca()));

        operacao[3].setTempoOcupacaoMaquinaPeca(0.7);
        txtP1M4.setText(Double.toString(operacao[3].getTempoOcupacaoMaquinaPeca()));

        operacao[13].setTempoOcupacaoMaquinaPeca(1.5);
        txtP2M4.setText(Double.toString(operacao[13].getTempoOcupacaoMaquinaPeca()));

        operacao[33].setTempoOcupacaoMaquinaPeca(2.6);
        txtP4M4.setText(Double.toString(operacao[33].getTempoOcupacaoMaquinaPeca()));

        operacao[4].setTempoOcupacaoMaquinaPeca(1);
        txtP1M5.setText(Double.toString(operacao[4].getTempoOcupacaoMaquinaPeca()));

       // operacao[14].setDescricao("P2M5");
       // operacao[14].setPeca(peca[1]);
       // operacao[14].setMaquina(maquina[4]);
        operacao[14].setTempoOcupacaoMaquinaPeca(1.8);
        txtP2M5.setText(Double.toString(operacao[14].getTempoOcupacaoMaquinaPeca()));

        operacao[24].setTempoOcupacaoMaquinaPeca(2.9);
        txtP3M5.setText(Double.toString(operacao[24].getTempoOcupacaoMaquinaPeca()));

        operacao[34].setTempoOcupacaoMaquinaPeca(1.9);
        txtP4M5.setText(Double.toString(operacao[34].getTempoOcupacaoMaquinaPeca()));

        operacao[5].setTempoOcupacaoMaquinaPeca(0.6);
        txtP1M6.setText(Double.toString(operacao[5].getTempoOcupacaoMaquinaPeca()));

        operacao[15].setTempoOcupacaoMaquinaPeca(11.6);
        txtP2M6.setText(Double.toString(operacao[15].getTempoOcupacaoMaquinaPeca()));

        operacao[35].setTempoOcupacaoMaquinaPeca(11.6);
        txtP4M6.setText(Double.toString(operacao[35].getTempoOcupacaoMaquinaPeca()));

        operacao[26].setTempoOcupacaoMaquinaPeca(2.6);
        txtP3M7.setText(Double.toString(operacao[26].getTempoOcupacaoMaquinaPeca()));

        operacao[36].setTempoOcupacaoMaquinaPeca(22.3);
        txtP4M7.setText(Double.toString(operacao[36].getTempoOcupacaoMaquinaPeca()));

        operacao[46].setTempoOcupacaoMaquinaPeca(0.7);
        txtP5M7.setText(Double.toString(operacao[46].getTempoOcupacaoMaquinaPeca()));

        operacao[27].setTempoOcupacaoMaquinaPeca(2.2);
        txtP3M8.setText(Double.toString(operacao[27].getTempoOcupacaoMaquinaPeca()));

        operacao[37].setTempoOcupacaoMaquinaPeca(1);
        txtP4M8.setText(Double.toString(operacao[37].getTempoOcupacaoMaquinaPeca()));

        operacao[47].setTempoOcupacaoMaquinaPeca(1);
        txtP5M8.setText(Double.toString(operacao[47].getTempoOcupacaoMaquinaPeca()));

        operacao[67].setTempoOcupacaoMaquinaPeca(2.8);
        txtP7M8.setText(Double.toString(operacao[67].getTempoOcupacaoMaquinaPeca()));

        operacao[18].setTempoOcupacaoMaquinaPeca(0.8);
        txtP2M9.setText(Double.toString(operacao[18].getTempoOcupacaoMaquinaPeca()));

      //  operacao[38].setDescricao("P4M9");
      //  operacao[38].setPeca(peca[3]);
      //  operacao[38].setMaquina(maquina[8]);
        operacao[38].setTempoOcupacaoMaquinaPeca(1.8);
        txtP4M9.setText(Double.toString(operacao[38].getTempoOcupacaoMaquinaPeca()));

       // operacao[48].setDescricao("P5M9");
      //  operacao[48].setPeca(peca[4]);
       // operacao[48].setMaquina(maquina[8]);
        operacao[48].setTempoOcupacaoMaquinaPeca(0.3);
        txtP5M9.setText(Double.toString(operacao[48].getTempoOcupacaoMaquinaPeca()));

        operacao[68].setTempoOcupacaoMaquinaPeca(0.8);
        txtP7M9.setText(Double.toString(operacao[68].getTempoOcupacaoMaquinaPeca()));

        operacao[19].setTempoOcupacaoMaquinaPeca(1.9);
        txtP2M10.setText(Double.toString(operacao[19].getTempoOcupacaoMaquinaPeca()));

        operacao[29].setTempoOcupacaoMaquinaPeca(0.9);
        txtP3M10.setText(Double.toString(operacao[29].getTempoOcupacaoMaquinaPeca()));

        operacao[39].setTempoOcupacaoMaquinaPeca(0.7);
        txtP4M10.setText(Double.toString(operacao[39].getTempoOcupacaoMaquinaPeca()));

        operacao[59].setTempoOcupacaoMaquinaPeca(107);
        txtP6M10.setText(Double.toString(operacao[59].getTempoOcupacaoMaquinaPeca()));


        //tempo total da operação qtde peca * tempo ocupação
        for(int i = 0; i < operacao.length; i++){            
            operacao[i].setTempoTotalOperacao(operacao[i].getTempoOcupacaoMaquinaPeca() * operacao[i].getPeca().getQuantidade());            
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCarregarValoresInciais;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMixProdutos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelCalculoOciosidade;
    private javax.swing.JPanel jPanelDadosMaquina;
    private javax.swing.JPanel jPanelMaqPeca;
    private javax.swing.JLabel lblData;
    private javax.swing.JTextField txtM1;
    private javax.swing.JTextField txtM10;
    private javax.swing.JTextField txtM2;
    private javax.swing.JTextField txtM3;
    private javax.swing.JTextField txtM4;
    private javax.swing.JTextField txtM5;
    private javax.swing.JTextField txtM6;
    private javax.swing.JTextField txtM7;
    private javax.swing.JTextField txtM8;
    private javax.swing.JTextField txtM9;
    private javax.swing.JTextField txtOcioM1;
    private javax.swing.JTextField txtOcioM10;
    private javax.swing.JTextField txtOcioM2;
    private javax.swing.JTextField txtOcioM3;
    private javax.swing.JTextField txtOcioM4;
    private javax.swing.JTextField txtOcioM5;
    private javax.swing.JTextField txtOcioM6;
    private javax.swing.JTextField txtOcioM7;
    private javax.swing.JTextField txtOcioM8;
    private javax.swing.JTextField txtOcioM9;
    private javax.swing.JTextField txtP1M1;
    private javax.swing.JTextField txtP1M10;
    private javax.swing.JTextField txtP1M2;
    private javax.swing.JTextField txtP1M3;
    private javax.swing.JTextField txtP1M4;
    private javax.swing.JTextField txtP1M5;
    private javax.swing.JTextField txtP1M6;
    private javax.swing.JTextField txtP1M7;
    private javax.swing.JTextField txtP1M8;
    private javax.swing.JTextField txtP1M9;
    private javax.swing.JTextField txtP2M1;
    private javax.swing.JTextField txtP2M10;
    private javax.swing.JTextField txtP2M2;
    private javax.swing.JTextField txtP2M3;
    private javax.swing.JTextField txtP2M4;
    private javax.swing.JTextField txtP2M5;
    private javax.swing.JTextField txtP2M6;
    private javax.swing.JTextField txtP2M7;
    private javax.swing.JTextField txtP2M8;
    private javax.swing.JTextField txtP2M9;
    private javax.swing.JTextField txtP3M1;
    private javax.swing.JTextField txtP3M10;
    private javax.swing.JTextField txtP3M2;
    private javax.swing.JTextField txtP3M3;
    private javax.swing.JTextField txtP3M4;
    private javax.swing.JTextField txtP3M5;
    private javax.swing.JTextField txtP3M6;
    private javax.swing.JTextField txtP3M7;
    private javax.swing.JTextField txtP3M8;
    private javax.swing.JTextField txtP3M9;
    private javax.swing.JTextField txtP4M1;
    private javax.swing.JTextField txtP4M10;
    private javax.swing.JTextField txtP4M2;
    private javax.swing.JTextField txtP4M3;
    private javax.swing.JTextField txtP4M4;
    private javax.swing.JTextField txtP4M5;
    private javax.swing.JTextField txtP4M6;
    private javax.swing.JTextField txtP4M7;
    private javax.swing.JTextField txtP4M8;
    private javax.swing.JTextField txtP4M9;
    private javax.swing.JTextField txtP5M1;
    private javax.swing.JTextField txtP5M10;
    private javax.swing.JTextField txtP5M2;
    private javax.swing.JTextField txtP5M3;
    private javax.swing.JTextField txtP5M4;
    private javax.swing.JTextField txtP5M5;
    private javax.swing.JTextField txtP5M6;
    private javax.swing.JTextField txtP5M7;
    private javax.swing.JTextField txtP5M8;
    private javax.swing.JTextField txtP5M9;
    private javax.swing.JTextField txtP6M1;
    private javax.swing.JTextField txtP6M10;
    private javax.swing.JTextField txtP6M2;
    private javax.swing.JTextField txtP6M3;
    private javax.swing.JTextField txtP6M4;
    private javax.swing.JTextField txtP6M5;
    private javax.swing.JTextField txtP6M6;
    private javax.swing.JTextField txtP6M7;
    private javax.swing.JTextField txtP6M8;
    private javax.swing.JTextField txtP6M9;
    private javax.swing.JTextField txtP7M1;
    private javax.swing.JTextField txtP7M10;
    private javax.swing.JTextField txtP7M2;
    private javax.swing.JTextField txtP7M3;
    private javax.swing.JTextField txtP7M4;
    private javax.swing.JTextField txtP7M5;
    private javax.swing.JTextField txtP7M6;
    private javax.swing.JTextField txtP7M7;
    private javax.swing.JTextField txtP7M8;
    private javax.swing.JTextField txtP7M9;
    private javax.swing.JTextField txtQtdeProd1;
    private javax.swing.JTextField txtQtdeProd2;
    private javax.swing.JTextField txtQtdeProd3;
    private javax.swing.JTextField txtQtdeProd4;
    private javax.swing.JTextField txtQtdeProd5;
    private javax.swing.JTextField txtQtdeProd6;
    private javax.swing.JTextField txtQtdeProd7;
    private javax.swing.JTextField txtTempOcupM1;
    private javax.swing.JTextField txtTempOcupM10;
    private javax.swing.JTextField txtTempOcupM2;
    private javax.swing.JTextField txtTempOcupM3;
    private javax.swing.JTextField txtTempOcupM4;
    private javax.swing.JTextField txtTempOcupM5;
    private javax.swing.JTextField txtTempOcupM6;
    private javax.swing.JTextField txtTempOcupM7;
    private javax.swing.JTextField txtTempOcupM8;
    private javax.swing.JTextField txtTempOcupM9;
    // End of variables declaration//GEN-END:variables
}
