/* 
   TABELAS SOMENTE PARA IDENTIFICAÇÃO DOS CAMPOS
   SCRIPT COMPLETO PARA CRIAÇÃO DO BANCO ESTÁ 
   NO ARQUIVO: scriptSQLDBSAO.sql
*/

CREATE TABLE TB_MAQUINA (
  ID_CODMAQ INT ,
  MQ_DESCRICAO VARCHAR(255),
  MQ_TEMPOTOTAL INT ,
  PRIMARY KEY (`ID_CODMAQ`));

CREATE TABLE TB_PECA (
  ID_CODPECA INT,
  PEC_DESCRICAO VARCHAR(255),
  PEC_QUANTIDADE INT,
  PEC_DIAMETRO DOUBLE,
  PEC_PERCURSO DOUBLE,
  PEC_AVANCO DOUBLE,
  PEC_MATERIAL DOUBLE,
  TB_TAYLOR DOUBLE,
  PRIMARY KEY (`ID_CODPECA`));

CREATE TABLE TB_OPERACAO (
  ID_CODOPERACAO INT,
  ID_CODMAQ INT,
  ID_CODPECA INT,
  OP_TEMPOMAQPEC DOUBLE,
  PRIMARY KEY (`ID_CODOPERACAO`),

  CONSTRAINT `FK_CODMAQOPERACAO`
    FOREIGN KEY (`ID_CODMAQ`)
    REFERENCES `myDBSAO`.`TB_MAQUINA` (`ID_CODMAQ`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CODPECAOPERACAO`
    FOREIGN KEY (`ID_CODPECA`)
    REFERENCES `myDBSAO`.`TB_PECA` (`ID_CODPECA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
COMMENT = '						';

CREATE TABLE TB_CUSTO (
  ID_CUSTO INT NOT NULL,
  CUST_SH DOUBLE NULL,
  CUST_CM DOUBLE NULL,
  CUST_KFT DOUBLE NULL,
  CUST_TFT DOUBLE NULL,
  CUST_CTU DOUBLE NULL,
  CUST_SM DOUBLE NULL,
  PRIMARY KEY (`ID_CUSTO`))

CREATE TABLE TB_IMPOSTO (
  ID_IMPOSTO INT NOT NULL,
  IMP_MC DOUBLE,
  IMP_TX DOUBLE,
  PRIMARY KEY (`ID_IMPOSTO`))

CREATE TABLE TB_TEMPO (
  ID_TEMPO INT,
  TMP_TC DOUBLE,
  TMP_VIDAFERRAMENTA DOUBLE,
  PRIMARY KEY (`ID_TEMPO`))

CREATE TABLE TB_VELOCIDADECORTE (
  ID_VELOCIDADECORTE INT,
  VEL_VCMC DOUBLE,
  VEL_VCMXP DOUBLE,
  VEL_VCMLIM DOUBLE,
  PRIMARY KEY (`ID_VELOCIDADECORTE`))
